graphite:
  image: hopsoft/graphite-statsd:latest
  ports:
   - "8481:80"

mongoAuthentication:
  image: mongo:latest

mongoValet:
  image: mongo:latest

mongoMaintenance:
  image: mongo:latest

mongoVehicle:
  image: mongo:latest

authentication:
  build: virtual-vehicles-authentication-docker/
  ports:
   - "8587:8587"
  links:
   - graphite:graphite
   - mongoAuthentication:mongoAuthentication

valet:
  build: virtual-vehicles-valet-docker/
  ports:
   - "8585:8585"
  links:
   - graphite:graphite
   - mongoValet:mongoValet
   - authentication:authentication

maintenance:
  build: virtual-vehicles-maintenance-docker/
  ports:
   - "8583:8583"
  links:
   - graphite:graphite
   - mongoMaintenance:mongoMaintenance
   - authentication:authentication

vehicle:
  build: virtual-vehicles-vehicle-docker/
  ports:
   - "8581:8581"
  links:
   - graphite:graphite
   - mongoVehicle:mongoVehicle
   - authentication:authentication
